#!/bin/bash

DIR="/opt/kingvpn"
ENV="$DIR/.env"
PORT_FILE="$DIR/port"

# Verificar si un puerto está en uso
is_port_in_use() {
    lsof -i :$1 >/dev/null 2>&1
}

# Iniciar panel
start_KINGVPN() {
    local port=$1

    if is_port_in_use $port; then
        echo "El puerto $port ya está en uso."
        return
    fi

    cd $DIR || { echo "No se encuentra $DIR"; return; }

    # Cargar NVM
    [ -s "/root/.nvm/nvm.sh" ] && \. "/root/.nvm/nvm.sh"

    # Crear .env
    rm -f "$ENV"
    echo "PORT=$port" > "$ENV"
    echo 'NODE_ENV="production"' >> "$ENV"
    echo "DATABASE_URL=\"file:$DIR/prisma/database.db\"" >> "$ENV"

    token1=$(node -e "console.log(require('crypto').randomBytes(100).toString('base64'))")
    token2=$(node -e "console.log(require('crypto').randomBytes(100).toString('base64'))")
    token3=$(node -e "console.log(require('crypto').randomBytes(100).toString('base64'))")

    echo "CSRF_SECRET=\"$token1\"" >> "$ENV"
    echo "JWT_SECRET_KEY=\"$token2\"" >> "$ENV"
    echo "JWT_SECRET_REFRESH=\"$token3\"" >> "$ENV"
    echo "ENCRYPT_FILES=\"7223fd56-e21d-4191-8867-f3c67601122a\"" >> "$ENV"

    # Build y migraciones
    npm run build
    npx prisma migrate deploy

    # Crear servicio systemd
    SERVICE="/etc/systemd/system/kingvpn.service"

    cat > "$SERVICE" <<EOF
[Unit]
Description=KINGVPN Panel
After=network.target

[Service]
WorkingDirectory=$DIR
ExecStart=/root/.nvm/versions/node/v18.20.4/bin/npm start
Restart=always
Environment=NVM_DIR=/root/.nvm
Environment=PATH=/root/.nvm/versions/node/v18.20.4/bin:/usr/bin:/bin

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable kingvpn
    systemctl restart kingvpn

    echo "$port" > "$PORT_FILE"

    echo "Iniciado con éxito!"
}

# Detener panel
stop_KINGVPN() {
    systemctl stop kingvpn
    systemctl disable kingvpn
    rm -f /etc/systemd/system/kingvpn.service
    systemctl daemon-reload

    rm -f "$PORT_FILE"
    echo "Detenido con éxito!"
}

show_menu() {
    clear
    echo "------------------------------------------------"
    printf "|                 %-29s|\n" "KINGVPN"
    echo "------------------------------------------------"

    if [ ! -s "$PORT_FILE" ]; then
        printf "| Acceso: %-37s|\n" "Desactivado"
        STATUS=0
    else
        PORT=$(cat $PORT_FILE)
        printf "| Acceso: %-37s|\n" "http://$(wget -qO- ipinfo.io/ip):$PORT"
        STATUS=1
    fi

    echo "------------------------------------------------"
    if [ "$STATUS" -eq 0 ]; then 
        echo "| 1 - Iniciar Panel                               |"
    else
        echo "| 1 - Detener Panel                               |"
    fi
    echo "| 0 - Salir                                       |"
    echo "------------------------------------------------"
    echo
    read -p " --> Seleccione una opcion: " option

    case $option in
        1)
            if [ "$STATUS" -eq 0 ]; then
                read -p "Puerto: " port
                start_KINGVPN $port
                read -n 1 -s -p "Presione para continuar..."
            else
                stop_KINGVPN
                read -n 1 -s -p "Presione para continuar..."
            fi
            ;;
        0)
            exit 0 ;;
        *)
            echo "Opción inválida"
            read -n 1 -s ;;
    esac
}

while true; do
    show_menu
done
